-- CONSULTE TODOS OS VEÍCULOS EXISTENTES NO BD, EXIBINDO A PLACA, MODELO E FABRICANTE DE CADA UM.'

SELECT VEICULO.PLACA, MODELO.NOME_MODELO, FABRICANTE.NOME_DO_FABRICANTE FROM VEICULO
JOIN MODELO ON VEICULO.CODIGO_MODELO = MODELO.CODIGO_MODELO
JOIN FABRICANTE ON MODELO.CODIGO_FABRICANTE = FABRICANTE.CODIGO_DO_FABRICANTE;

-- CONSULTE A QUANTIDADE DE REGISTROS EXISTENTES NA TABELA VEICULO CUJO ANO DE FABRICAÇÃO É DIFERENTE DO ANO DO MODELO.'

SELECT COUNT(*) FROM VEICULO WHERE ANO_FABRICACAO <> ANO_MODELO;

-- CONSULTE A QUANTIDADE DE VEÍCULOS EXISTENTES POR ANO DE FABRICAÇÃO, CONSIDERANDO APENAS OS ANOS DE FABRICAÇÃO EXISTENTES NA TABELA VEICULO.'

SELECT ANO_FABRICACAO, COUNT(*) AS QUANTIDADE_VEICULOS FROM VEICULO GROUP BY ANO_FABRICACAO;

-- CONSULTE TODOS OS NOMES DE MODELO DOS FABRICANTES “FORD”, “FIAT” E “HONDA”.'

SELECT MODELO.NOME_MODELO FROM MODELO
JOIN FABRICANTE ON MODELO.CODIGO_FABRICANTE = FABRICANTE.CODIGO_DO_FABRICANTE WHERE FABRICANTE.NOME_DO_FABRICANTE IN ('FORD', 'FIAT', 'HONDA');

-- CONSULTE OS VEÍCULOS QUE TEM A PLACA TERMINANDO EM “123”.'

SELECT VEICULO.PLACA, MODELO.NOME_MODELO FROM VEICULO JOIN MODELO ON VEICULO.CODIGO_MODELO = MODELO.CODIGO_MODELO WHERE VEICULO.PLACA LIKE '%123';

-- CONSULTE OS VEÍCULOS FABRICADOS NOS ANOS DE 2001, 2002, 2003, 2004, 2006, 2007 E 2008.'

SELECT * FROM VEICULO WHERE ANO_FABRICACAO IN (2001, 2002, 2003, 2004, 2006, 2007, 2008);

-- CONSULTE OS VEÍCULOS COM ANO DO MODELO ENTRE 1999 E 2016;'

SELECT * FROM VEICULO WHERE ANO_MODELO BETWEEN 1999 AND 2016;

-- CONSULTE TODOS OS VEÍCULOS DO MODELO “GOL”, DO FABRICANTE “VOLKSWAGEN”.'

SELECT VEICULO.PLACA FROM VEICULO
JOIN MODELO ON VEICULO.CODIGO_MODELO = MODELO.CODIGO_MODELO
JOIN FABRICANTE ON MODELO.CODIGO_FABRICANTE = FABRICANTE.CODIGO_DO_FABRICANTE WHERE MODELO.NOME_MODELO = 'GOL' AND FABRICANTE.NOME_DO_FABRICANTE = 'VOLKSWAGEN';

-- CONSULTE OS VEÍCULOS DO MODELO “GOL”, DO FABRICANTE “VOLKSWAGEN”, QUE FORAM FABRICADOS EM 2010 OU TÊM PLACA INICIANDO COM “X”.'

SELECT VEICULO.PLACA FROM VEICULO
JOIN MODELO ON VEICULO.CODIGO_MODELO = MODELO.CODIGO_MODELO
JOIN FABRICANTE ON MODELO.CODIGO_FABRICANTE = FABRICANTE.CODIGO_DO_FABRICANTE WHERE MODELO.NOME_MODELO = 'GOL' 
AND FABRICANTE.NOME_DO_FABRICANTE = 'VOLKSWAGEN'
AND (VEICULO.ANO_FABRICACAO = 2010 OR VEICULO.PLACA LIKE 'X%');

-- CONSULTE TODOS OS VEÍCULOS DO FABRICANTE “RENAULT” QUE NÃO SEJAM DOS MODELOS “CLIO” NEM “SANDERO”, E QUE FORAM FABRICADOS ANTES DE 2015.'

SELECT VEICULO.PLACA FROM VEICULO
JOIN MODELO ON VEICULO.CODIGO_MODELO = MODELO.CODIGO_MODELO
JOIN FABRICANTE ON MODELO.CODIGO_FABRICANTE = FABRICANTE.CODIGO_DO_FABRICANTE WHERE FABRICANTE.NOME_DO_FABRICANTE = 'RENAULT'
AND MODELO.NOME_MODELO NOT IN ('CLIO', 'SANDERO')
AND VEICULO.ANO_FABRICACAO < 2015;

-- CONSULTE A LISTA DE MODELOS EXISTENTES NA TABELA MODELO QUE NÃO POSSUEM VEÍCULOS ASSOCIADOS NA TABELA VEICULO.'

SELECT NOME_MODELO FROM MODELO WHERE CODIGO_MODELO NOT IN (SELECT CODIGO_MODELO FROM VEICULO);

-- CRIE UM COMANDO PARA ALTERAR PARA 2016 O ANO DE FABRICAÇÃO DE TODOS OS VEÍCULOS DO MODELO “PALIO”, DO FABRICANTE “FIAT”, QUE ESTÃO REGISTRADOS COM ANO DE FABRICAÇÃO EM 1996.'

UPDATE VEICULO SET ANO_FABRICACAO = 2016 WHERE CODIGO_MODELO IN (
SELECT CODIGO_MODELO FROM MODELO WHERE NOME_MODELO = 'PALIO'
AND CODIGO_FABRICANTE = (SELECT CODIGO_DO_FABRICANTE FROM FABRICANTE WHERE NOME_DO_FABRICANTE = 'FIAT'))
AND ANO_FABRICACAO = 1996;
